global:
  imagePullPolicy: Always

frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
    targetPort: 8080
  ingress:
    host: front-oreshek66.2sem.students-projects.ru
    secretName: 2sem-students-projects-wildcard-secret
    path: /
    pathType: Prefix
  containerPort: 8080
  image: fursov231/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgres:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
    vaultEnabled: false
  service:
    port: 8080
    targetPort: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  image: fursov231/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  vpa:
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          controlledResources: ["cpu", "memory"]

backend-report:
  env:
    port: 8080
  service:
    port: 8080
  replicas: 1
  strategy:
    type: Recreate
  image: fursov231/sausage-backend-report:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  hpa:
    resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization

infra:
  postgresql:
    image: postgres:15
    port: 5432
    storageSize: 128Mi
    username: store
    password: storepassword
    database: sausage-store
    storageClassName: yc-network-hdd
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        cpu: "100m"
        memory: "128Mi"
  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    containerPort: 27017
    reportUser: reportuser
    reportPassword: reportpassword
    reportDb: sausage-store
    storage: 128Mi
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        cpu: "100m"
        memory: "256Mi"
